use super::python_env::api_mock_python_dir;
use super::types::ApiMockPythonScript;
use crate::app::api_client::{
    ApiMethod, ApiParam, ApiPrimitiveType, ApiRouteRow, ApiSchema, ApiSchemaKind, ApiSpecModel,
};
use std::path::PathBuf;
use std::process::Command;
use std::sync::mpsc::{self, Receiver};

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ApiMockTyCheckResult {
    pub route_idx: usize,
    pub ok: bool,
    pub message: String,
}

pub fn spawn_api_mock_ty_check(
    route_idx: usize,
    method: ApiMethod,
    path: String,
    route: ApiRouteRow,
    model: ApiSpecModel,
    script: ApiMockPythonScript,
) -> Receiver<ApiMockTyCheckResult> {
    let (tx, rx) = mpsc::channel();
    std::thread::spawn(move || {
        let result = run_api_mock_ty_check(route_idx, method, &path, &route, &model, &script);
        let _ = tx.send(result);
    });
    rx
}

fn run_api_mock_ty_check(
    route_idx: usize,
    method: ApiMethod,
    path: &str,
    route: &ApiRouteRow,
    model: &ApiSpecModel,
    script: &ApiMockPythonScript,
) -> ApiMockTyCheckResult {
    let source = build_api_mock_ty_source(method, path, route, model, script);
    let dir = api_mock_python_dir().join("ty-check");
    if let Err(err) = std::fs::create_dir_all(&dir) {
        return ApiMockTyCheckResult {
            route_idx,
            ok: false,
            message: err.to_string(),
        };
    }
    let file = dir.join(format!("mock_route_{}.py", route_idx));
    if let Err(err) = std::fs::write(&file, source) {
        return ApiMockTyCheckResult {
            route_idx,
            ok: false,
            message: err.to_string(),
        };
    }
    run_ty(route_idx, &file)
}

fn run_ty(route_idx: usize, file: &PathBuf) -> ApiMockTyCheckResult {
    let output = Command::new("ty").arg("check").arg(file).output();
    match output {
        Ok(output) => {
            let mut message = String::new();
            message.push_str(String::from_utf8_lossy(&output.stdout).trim());
            let err = String::from_utf8_lossy(&output.stderr);
            if !err.trim().is_empty() {
                if !message.is_empty() {
                    message.push('\n');
                }
                message.push_str(err.trim());
            }
            if message.is_empty() {
                message = if output.status.success() {
                    "Ty check passed".to_string()
                } else {
                    "Ty check failed".to_string()
                };
            }
            ApiMockTyCheckResult {
                route_idx,
                ok: output.status.success(),
                message,
            }
        }
        Err(err) => ApiMockTyCheckResult {
            route_idx,
            ok: false,
            message: format!("ty not available: {}", err),
        },
    }
}

pub fn build_api_mock_ty_source(
    method: ApiMethod,
    path: &str,
    route: &ApiRouteRow,
    model: &ApiSpecModel,
    script: &ApiMockPythonScript,
) -> String {
    let mut out = String::with_capacity(script.prelude.len() + script.body.len() + 1024);
    out.push_str("from __future__ import annotations\n");
    out.push_str("from dataclasses import dataclass\n");
    out.push_str("from typing import Any\n\n");
    out.push_str("# Generated by RRiter. Locked route contract.\n");
    out.push_str(&format!("# {} {}\n\n", method.as_str(), path));
    out.push_str("@dataclass\nclass Request:\n");
    out.push_str("    method: str\n    path: str\n    headers: dict[str, str]\n\n");
    push_param_class(&mut out, "Query", &route.query_params);
    push_body_class(&mut out, route, model);
    out.push_str("@dataclass\nclass Fields:\n    values: dict[str, Any]\n\n");
    out.push_str("@dataclass\nclass Output:\n    status: int = 200\n    headers: dict[str, str] | None = None\n    json: Any | None = None\n    text: str | None = None\n\n");
    out.push_str("def json_response(data: Any, status: int = 200, headers: dict[str, str] | None = None) -> dict[str, Any]: ...\n");
    out.push_str("def text_response(text: str, status: int = 200, headers: dict[str, str] | None = None) -> dict[str, Any]: ...\n");
    out.push_str("def error_response(message: str, status: int = 500) -> dict[str, Any]: ...\n\n");
    if !script.prelude.trim().is_empty() {
        out.push_str("# User prelude\n");
        out.push_str(&script.prelude);
        out.push_str("\n\n");
    }
    out.push_str("def handler(req: Request");
    for name in path_param_names(path) {
        out.push_str(", ");
        out.push_str(&sanitize_python_param(&name));
        out.push_str(": str");
    }
    out.push_str(", query: Query, body: Body | None, fields: Fields) -> dict[str, Any]:\n");
    if script.body.trim().is_empty() {
        out.push_str("    return json_response({})\n");
    } else {
        for line in script.body.lines() {
            out.push_str("    ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

fn push_param_class(out: &mut String, name: &str, params: &[ApiParam]) {
    out.push_str("@dataclass\nclass ");
    out.push_str(name);
    out.push_str(":\n");
    if params.is_empty() {
        out.push_str("    pass\n\n");
        return;
    }
    for param in params {
        out.push_str("    ");
        out.push_str(&sanitize_python_param(&param.name));
        out.push_str(": ");
        out.push_str(python_primitive_type(param.primitive_type));
        if !param.required {
            out.push_str(" | None = None");
        }
        out.push('\n');
    }
    out.push('\n');
}

fn push_body_class(out: &mut String, route: &ApiRouteRow, model: &ApiSpecModel) {
    out.push_str("@dataclass\nclass Body:\n");
    let Some(schema_ref) = route.request_body.as_ref().and_then(|body| body.schema) else {
        out.push_str("    pass\n\n");
        return;
    };
    let Some(schema) = model.schema_arena.get(schema_ref.0) else {
        out.push_str("    pass\n\n");
        return;
    };
    if schema.properties.is_empty() {
        out.push_str("    raw: Any | None = None\n\n");
        return;
    }
    for prop in &schema.properties {
        let field_ty = model
            .schema_arena
            .get(prop.schema.0)
            .map(schema_python_type)
            .unwrap_or("Any");
        out.push_str("    ");
        out.push_str(&sanitize_python_param(&prop.name));
        out.push_str(": ");
        out.push_str(field_ty);
        if !prop.required {
            out.push_str(" | None = None");
        }
        out.push('\n');
    }
    out.push('\n');
}

fn schema_python_type(schema: &ApiSchema) -> &'static str {
    match schema.kind {
        ApiSchemaKind::String
        | ApiSchemaKind::Date
        | ApiSchemaKind::DateTime
        | ApiSchemaKind::Bytes => "str",
        ApiSchemaKind::Integer => "int",
        ApiSchemaKind::Number => "float",
        ApiSchemaKind::Boolean => "bool",
        ApiSchemaKind::Array => "list[Any]",
        ApiSchemaKind::Object => "dict[str, Any]",
        ApiSchemaKind::Unknown => "Any",
    }
}

fn python_primitive_type(kind: ApiPrimitiveType) -> &'static str {
    match kind {
        ApiPrimitiveType::String
        | ApiPrimitiveType::Date
        | ApiPrimitiveType::DateTime
        | ApiPrimitiveType::Bytes => "str",
        ApiPrimitiveType::Integer => "int",
        ApiPrimitiveType::Number => "float",
        ApiPrimitiveType::Boolean => "bool",
        ApiPrimitiveType::Array => "list[str]",
        ApiPrimitiveType::Object | ApiPrimitiveType::Unknown => "Any",
    }
}

fn path_param_names(path: &str) -> Vec<String> {
    path.split('/')
        .filter_map(|part| {
            part.strip_prefix('{')
                .and_then(|part| part.strip_suffix('}'))
                .map(str::to_string)
        })
        .collect()
}

fn sanitize_python_param(name: &str) -> String {
    let mut out = String::new();
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() || out.as_bytes().first().is_some_and(u8::is_ascii_digit) {
        out.insert(0, '_');
    }
    if matches!(out.as_str(), "req" | "query" | "body" | "fields") {
        out.push_str("_param");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::app::api_client::ApiParamLocation;

    #[test]
    fn ty_source_contains_locked_signature_and_models() {
        let route = ApiRouteRow {
            tag: String::new(),
            method: ApiMethod::Get,
            path: "/users/{id}".to_string(),
            summary: String::new(),
            operation_id: String::new(),
            security: None,
            path_params: Vec::new(),
            query_params: vec![ApiParam {
                name: "page".to_string(),
                location: ApiParamLocation::Query,
                required: false,
                primitive_type: ApiPrimitiveType::Integer,
                item_type: None,
                enum_values: Vec::new(),
                default_value: None,
                example: None,
                examples: Vec::new(),
                description: String::new(),
            }],
            request_body: None,
            responses: Vec::new(),
        };
        let model = ApiSpecModel::default();
        let source = build_api_mock_ty_source(
            ApiMethod::Get,
            "/users/{id}",
            &route,
            &model,
            &ApiMockPythonScript {
                prelude: String::new(),
                body: "return json_response({\"id\": id})".to_string(),
                timeout_ms: 1000,
            },
        );

        assert!(source.contains("class Query"));
        assert!(source.contains("page: int | None = None"));
        assert!(source.contains("def handler(req: Request, id: str, query: Query"));
    }
}
