use super::{CommandInfo, KeyContext};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(usize)]
pub enum Command {
    SettingsCopyInstallerLog, MarkdownToggleMode, TerminalToggleFocus, TerminalClose,
    SettingsToggle, ViewToggleFps, ViewToggleProblems, SearchProjectOpen,
    FileTreeUndo, FileTreeCopy, FileTreeCut, FileTreePaste, TabsSwitchNext, TabsSwitchPrevious,
    TerminalCloseTab, GitCopySelection, DatabaseQueryRun, DatabaseQueryComplete, MarkdownToggleToc,
    FileOpen, AppQuit, TabsCloseAll, SearchEditorOpen, EditorExpandSelection, FileSave,
    EditorUndo, EditorRedo, EditorToggleLineComment, EditorComplete, TabsClose, EditCopy,
    EditCut, EditPaste, EditSelectAll, PdfCopy, FileTreeRename, DatabaseTableCopy,
    DatabaseTableUndo, DatabaseTableAddRow, DatabaseTableFilterComplete, LspCodeActions,
    SearchProjectRun, ApiMockRunRouteTools, DatabaseTableCommitCellLiteral,
    EditorGitDiffPrevHunk, EditorGitDiffNextHunk, GitStageAll, GitUnstageAll, GitPush, GitFetch,
    GitPull, GitRefresh, GitToggleGraph, GitToggleLogs, LspRestartServer, LspFixAll,
    ApiImportOpenapiFile, ApiSendRequest, ApiMockToggleServer, ApiMockExportOpenapi,
    DatabaseRefreshSelected, DatabaseTableRefresh, DatabaseTableSave, DatabaseTablePreviewSql,
    DatabaseQueryExplain, DatabaseQueryExplainAnalyze, DatabaseQueryFormat, DatabaseQueryNextDiagnostic,
}

pub const COMMANDS: &[CommandInfo] = &[
    CommandInfo { command: Command::SettingsCopyInstallerLog, id: "settings.copy_installer_log", label: "Копировать журнал установки", context: KeyContext::Settings, defaults: &["mod+c"] },
    CommandInfo { command: Command::MarkdownToggleMode, id: "markdown.toggle_mode", label: "Markdown: режим чтения/редактирования", context: KeyContext::Markdown, defaults: &["mod+shift+v"] },
    CommandInfo { command: Command::TerminalToggleFocus, id: "terminal.toggle_focus", label: "Показать/скрыть терминал", context: KeyContext::Global, defaults: &["alt+q"] },
    CommandInfo { command: Command::TerminalClose, id: "terminal.close", label: "Закрыть терминал", context: KeyContext::Global, defaults: &["alt+shift+q"] },
    CommandInfo { command: Command::SettingsToggle, id: "settings.toggle", label: "Открыть/закрыть настройки", context: KeyContext::Global, defaults: &["f1"] },
    CommandInfo { command: Command::ViewToggleFps, id: "view.toggle_fps", label: "Показать/скрыть FPS", context: KeyContext::Global, defaults: &["f8"] },
    CommandInfo { command: Command::ViewToggleProblems, id: "view.toggle_problems", label: "Показать/скрыть проблемы", context: KeyContext::Global, defaults: &["alt+w"] },
    CommandInfo { command: Command::SearchProjectOpen, id: "search.project.open", label: "Поиск по проекту", context: KeyContext::Global, defaults: &["mod+shift+f"] },
    CommandInfo { command: Command::FileTreeUndo, id: "file_tree.undo", label: "Отменить операцию с файлами", context: KeyContext::FileTree, defaults: &["mod+z"] },
    CommandInfo { command: Command::FileTreeCopy, id: "file_tree.copy", label: "Копировать файлы", context: KeyContext::FileTree, defaults: &["mod+c"] },
    CommandInfo { command: Command::FileTreeCut, id: "file_tree.cut", label: "Вырезать файлы", context: KeyContext::FileTree, defaults: &["mod+x"] },
    CommandInfo { command: Command::FileTreePaste, id: "file_tree.paste", label: "Вставить файлы", context: KeyContext::FileTree, defaults: &["mod+v"] },
    CommandInfo { command: Command::TabsSwitchNext, id: "tabs.switch_next", label: "Следующая вкладка", context: KeyContext::Global, defaults: &["mod+pagedown"] },
    CommandInfo { command: Command::TabsSwitchPrevious, id: "tabs.switch_previous", label: "Предыдущая вкладка", context: KeyContext::Global, defaults: &["mod+pageup"] },
    CommandInfo { command: Command::TerminalCloseTab, id: "terminal.close_tab", label: "Закрыть вкладку терминала", context: KeyContext::Terminal, defaults: &["mod+4"] },
    CommandInfo { command: Command::GitCopySelection, id: "git.copy_selection", label: "Копировать выделение Git", context: KeyContext::Git, defaults: &["mod+c"] },
    CommandInfo { command: Command::DatabaseQueryRun, id: "database.query.run", label: "Выполнить SQL-запрос", context: KeyContext::DatabaseQuery, defaults: &["mod+enter", "mod+numpadenter"] },
    CommandInfo { command: Command::DatabaseQueryComplete, id: "database.query.complete", label: "Дополнение SQL", context: KeyContext::DatabaseQuery, defaults: &["mod+space"] },
    CommandInfo { command: Command::MarkdownToggleToc, id: "markdown.toggle_toc", label: "Оглавление Markdown", context: KeyContext::Markdown, defaults: &["mod+shift+o"] },
    CommandInfo { command: Command::FileOpen, id: "file.open", label: "Открыть файл", context: KeyContext::Editor, defaults: &["mod+o", "mod+shift+o"] },
    CommandInfo { command: Command::AppQuit, id: "app.quit", label: "Выйти из RRiter", context: KeyContext::Welcome, defaults: &["mod+q"] },
    CommandInfo { command: Command::TabsCloseAll, id: "tabs.close_all", label: "Закрыть все вкладки / документ", context: KeyContext::Editor, defaults: &["mod+q"] },
    CommandInfo { command: Command::SearchEditorOpen, id: "search.editor.open", label: "Найти в файле", context: KeyContext::Editor, defaults: &["mod+f"] },
    CommandInfo { command: Command::EditorExpandSelection, id: "editor.expand_selection", label: "Расширить выделение", context: KeyContext::Editor, defaults: &["mod+w"] },
    CommandInfo { command: Command::FileSave, id: "file.save", label: "Сохранить файл", context: KeyContext::Editor, defaults: &["mod+s"] },
    CommandInfo { command: Command::EditorUndo, id: "editor.undo", label: "Отменить", context: KeyContext::Editor, defaults: &["mod+z"] },
    CommandInfo { command: Command::EditorRedo, id: "editor.redo", label: "Повторить", context: KeyContext::Editor, defaults: &["mod+y", "mod+shift+z"] },
    CommandInfo { command: Command::EditorToggleLineComment, id: "editor.toggle_line_comment", label: "Закомментировать строку", context: KeyContext::Editor, defaults: &["mod+/"] },
    CommandInfo { command: Command::EditorComplete, id: "editor.complete", label: "Автодополнение", context: KeyContext::Editor, defaults: &["mod+space"] },
    CommandInfo { command: Command::TabsClose, id: "tabs.close", label: "Закрыть вкладку", context: KeyContext::Editor, defaults: &["mod+4"] },
    CommandInfo { command: Command::EditCopy, id: "edit.copy", label: "Копировать", context: KeyContext::Editor, defaults: &["mod+c"] },
    CommandInfo { command: Command::EditCut, id: "edit.cut", label: "Вырезать", context: KeyContext::Editor, defaults: &["mod+x"] },
    CommandInfo { command: Command::EditPaste, id: "edit.paste", label: "Вставить", context: KeyContext::Editor, defaults: &["mod+v"] },
    CommandInfo { command: Command::EditSelectAll, id: "edit.select_all", label: "Выделить всё", context: KeyContext::Editor, defaults: &["mod+a"] },
    CommandInfo { command: Command::PdfCopy, id: "pdf.copy", label: "Копировать текст PDF", context: KeyContext::Pdf, defaults: &["mod+c"] },
    CommandInfo { command: Command::FileTreeRename, id: "file_tree.rename", label: "Переименовать файл", context: KeyContext::FileTree, defaults: &["f2"] },
    CommandInfo { command: Command::DatabaseTableCopy, id: "database.table.copy", label: "Копировать строки", context: KeyContext::DatabaseTable, defaults: &["mod+c"] },
    CommandInfo { command: Command::DatabaseTableUndo, id: "database.table.undo", label: "Отменить изменение таблицы", context: KeyContext::DatabaseTable, defaults: &["mod+z"] },
    CommandInfo { command: Command::DatabaseTableAddRow, id: "database.table.add_row", label: "Добавить строку", context: KeyContext::DatabaseTable, defaults: &["insert"] },
    CommandInfo { command: Command::DatabaseTableFilterComplete, id: "database.table.filter_complete", label: "Дополнение фильтра таблицы", context: KeyContext::DatabaseTable, defaults: &["mod+space"] },
    CommandInfo { command: Command::LspCodeActions, id: "lsp.code_actions", label: "Быстрые действия LSP", context: KeyContext::Editor, defaults: &["alt+enter"] },
    CommandInfo { command: Command::SearchProjectRun, id: "search.project.run", label: "Запустить поиск по проекту", context: KeyContext::ProjectSearch, defaults: &["mod+enter", "mod+numpadenter"] },
    CommandInfo { command: Command::ApiMockRunRouteTools, id: "api.mock.run_route_tools", label: "API Mock: инструменты маршрута", context: KeyContext::ApiClient, defaults: &["alt+enter"] },
    CommandInfo { command: Command::DatabaseTableCommitCellLiteral, id: "database.table.commit_cell_literal", label: "Записать значение ячейки буквально", context: KeyContext::DatabaseTable, defaults: &["mod+enter", "mod+numpadenter"] },
    CommandInfo { command: Command::EditorGitDiffPrevHunk, id: "editor.git_diff.prev_hunk", label: "Предыдущий Git hunk", context: KeyContext::Editor, defaults: &[] },
    CommandInfo { command: Command::EditorGitDiffNextHunk, id: "editor.git_diff.next_hunk", label: "Следующий Git hunk", context: KeyContext::Editor, defaults: &[] },
    CommandInfo { command: Command::GitStageAll, id: "git.stage_all", label: "Добавить всё в stage", context: KeyContext::Global, defaults: &[] },
    CommandInfo { command: Command::GitUnstageAll, id: "git.unstage_all", label: "Убрать всё из stage", context: KeyContext::Global, defaults: &[] },
    CommandInfo { command: Command::GitPush, id: "git.push", label: "Git: отправить (push)", context: KeyContext::Global, defaults: &[] },
    CommandInfo { command: Command::GitFetch, id: "git.fetch", label: "Git: получить (fetch)", context: KeyContext::Global, defaults: &[] },
    CommandInfo { command: Command::GitPull, id: "git.pull", label: "Git: вытянуть (pull)", context: KeyContext::Global, defaults: &[] },
    CommandInfo { command: Command::GitRefresh, id: "git.refresh", label: "Обновить Git", context: KeyContext::Global, defaults: &[] },
    CommandInfo { command: Command::GitToggleGraph, id: "git.toggle_graph", label: "Показать/скрыть граф Git", context: KeyContext::Global, defaults: &[] },
    CommandInfo { command: Command::GitToggleLogs, id: "git.toggle_logs", label: "Показать/скрыть журнал Git", context: KeyContext::Global, defaults: &[] },
    CommandInfo { command: Command::LspRestartServer, id: "lsp.restart_server", label: "Перезапустить LSP", context: KeyContext::Editor, defaults: &[] },
    CommandInfo { command: Command::LspFixAll, id: "lsp.fix_all", label: "Исправить всё (LSP)", context: KeyContext::Editor, defaults: &[] },
    CommandInfo { command: Command::ApiImportOpenapiFile, id: "api.import_openapi_file", label: "Импортировать OpenAPI-файл", context: KeyContext::ApiClient, defaults: &[] },
    CommandInfo { command: Command::ApiSendRequest, id: "api.send_request", label: "Отправить запрос", context: KeyContext::ApiClient, defaults: &[] },
    CommandInfo { command: Command::ApiMockToggleServer, id: "api.mock.toggle_server", label: "Запустить/остановить API Mock", context: KeyContext::ApiClient, defaults: &[] },
    CommandInfo { command: Command::ApiMockExportOpenapi, id: "api.mock.export_openapi", label: "Экспортировать OpenAPI", context: KeyContext::ApiClient, defaults: &[] },
    CommandInfo { command: Command::DatabaseRefreshSelected, id: "database.refresh_selected", label: "Обновить подключение БД", context: KeyContext::Global, defaults: &[] },
    CommandInfo { command: Command::DatabaseTableRefresh, id: "database.table.refresh", label: "Обновить таблицу", context: KeyContext::DatabaseTable, defaults: &[] },
    CommandInfo { command: Command::DatabaseTableSave, id: "database.table.save", label: "Сохранить изменения таблицы", context: KeyContext::DatabaseTable, defaults: &[] },
    CommandInfo { command: Command::DatabaseTablePreviewSql, id: "database.table.preview_sql", label: "Предпросмотр SQL изменений", context: KeyContext::DatabaseTable, defaults: &[] },
    CommandInfo { command: Command::DatabaseQueryExplain, id: "database.query.explain", label: "План запроса (EXPLAIN)", context: KeyContext::DatabaseQuery, defaults: &[] },
    CommandInfo { command: Command::DatabaseQueryExplainAnalyze, id: "database.query.explain_analyze", label: "План с анализом", context: KeyContext::DatabaseQuery, defaults: &[] },
    CommandInfo { command: Command::DatabaseQueryFormat, id: "database.query.format", label: "Форматировать SQL", context: KeyContext::DatabaseQuery, defaults: &[] },
    CommandInfo { command: Command::DatabaseQueryNextDiagnostic, id: "database.query.next_diagnostic", label: "Следующая ошибка SQL", context: KeyContext::DatabaseQuery, defaults: &[] },
];
