#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ApiMockContractFieldGroup {
    Path,
    Query,
    Body,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ApiMockContractFieldProp {
    Required,
    Nullable,
    Default,
    Enum,
    MinLength,
    MaxLength,
    Pattern,
    Minimum,
    Maximum,
    MinItems,
    MaxItems,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ThemeTarget {
    Both,
    Editor,
    Ui,
}

/// Уникальный идентификатор UI элемента
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum UiId {
    // Welcome screen
    WelcomeNewFile,
    WelcomeOpenFile,
    WelcomeIdeMode,
    WelcomeRecentFile(usize),

    // Dialog
    DialogSave,
    DialogDiscard,
    DialogCancel,

    // Settings tabs
    SettingsTab(usize),
    SettingsThemePick(ThemeTarget, crate::theme::ThemeId),
    SettingsThemeLinked,
    SettingsEditorCtrlWheelAdjust(i8),
    SettingsDatabaseAdjust(usize, i8),
    SettingsKeymapFilter,
    SettingsKeymapAdd(usize),
    SettingsKeymapRemove(usize, usize),
    SettingsKeymapReset(usize),
    SettingsKeymapResetAll,
    SettingsKeymapConflictAccept,
    SettingsKeymapConflictCancel,
    SettingsKeymapScrollY,

    // Settings IDE
    SettingsIdeAddWorkspace,
    SettingsIdeRemoveWorkspace(usize),
    SettingsIdeAddIgnore,
    SettingsIdeRemoveIgnore(usize),
    SettingsIdeIgnoreInput,
    SettingsIdeScrollY,
    SettingsFaqScrollY,
    SettingsGeneralScrollY,
    SettingsDatabaseScrollY,
    SettingsAppearanceScrollY,

    // Settings platform/tooling
    SettingsToolPick(usize),
    SettingsToolClear(usize),
    SettingsToolInstall(usize),
    SettingsOpenToolInstallLog,
    SettingsCloseToolInstallLog,
    SettingsCancelToolInstall,
    SettingsCopyToolInstallLog,
    SettingsToolInstallLogBackdrop,
    SettingsToolInstallLogBody,
    SettingsToolInstallLogScrollY,
    SettingsOpenDirectory(usize),
    SettingsCopyGraphicsDiagnostics,
    SettingsRefreshTools,
    SettingsDartToggleSupport,
    SettingsDartToggleWorkspaceAnalysis,
    SettingsDartCycleClosingLabels,
    SettingsDartAdjustNesting(i8),
    SettingsDartAdjustBlockLines(i8),
    SettingsDartRestart,
    SettingsDartOpenLog,
    SettingsRustToggleEnabled,
    SettingsRustToggleCheckCommand,
    SettingsRustRestart,

    // LSP panel
    LspServerRestart(usize),
    LspServerToggle(usize),
    LspServerStop(usize),
    LspServerLogs(usize),
    LspServerClearLogs(usize),
    LspServerFixAll(usize),
    LspLogFoldToggle(usize, usize), // (server_idx, line_idx)
    LspLogsFilterInput(usize),
    LspLogsFilterClear(usize),
    LspLogsFilterCase(usize),
    LspLogsFilterSend(usize),
    LspLogsFilterRecv(usize),
    LspLogsFilterOther(usize),

    // API client
    ApiImportAdd,
    ApiImportFile,
    ApiImportUrl,
    ApiImportUrlInput,
    ApiImportUrlConfirm,
    ApiSpecSelect(usize),
    ApiSpecOpen(usize),
    ApiSpecRefresh(usize),
    ApiSpecRemove(usize),
    ApiSpecRemoveConfirm,
    ApiSpecRemoveCancel,
    ApiAuthRoot,
    ApiRoutesRoot,
    ApiRouteFilterInput,
    ApiRouteFilterClear,
    ApiRouteTag(usize),
    ApiRouteRow(usize),
    ApiRoutePathText(usize),
    ApiRouteSummaryText(usize),
    ApiRouteDescriptionText(usize),
    ApiServerSelect(usize),
    ApiAuthValue(usize),
    ApiAuthRefreshToken(usize),
    ApiAuthUsername(usize),
    ApiAuthPassword(usize),
    ApiAuthAccessSave(usize),
    ApiAuthAccessClear(usize),
    ApiAuthRefreshSave(usize),
    ApiAuthRefreshClear(usize),
    ApiAuthSave(usize),
    ApiAuthClear(usize),
    ApiTryRequest,
    ApiPathParamInput(usize, usize),
    ApiQueryParamInput(usize, usize),
    ApiPathParamAllowedValue(usize, usize, usize),
    ApiQueryParamAllowedValue(usize, usize, usize),
    ApiBodyInput(usize),
    ApiInputExampleTab(usize),
    ApiInputSchemaTab(usize),
    ApiInputSchemaMenu(usize),
    ApiInputSchemaMenuItem(usize, usize),
    ApiInputSchemaBody(usize),
    ApiInputSchemaFold(usize, usize),
    ApiBodyScrollY(usize),
    ApiBodyScrollX(usize),
    ApiBodyFieldInput(usize, usize),
    ApiBodyAllowedValue(usize, usize, usize),
    ApiBodyFilePick(usize, usize),
    ApiOutputExampleTab(usize),
    ApiOutputSchemaTab(usize),
    ApiOutputStatusTab(usize, usize),
    ApiOutputSchemaMenu(usize),
    ApiOutputSchemaMenuScrollY(usize),
    ApiOutputSchemaMenuItem(usize, usize),
    ApiOutputSchemaBody(usize),
    ApiOutputSchemaFold(usize, usize),
    ApiOutputScrollY(usize),
    ApiOutputScrollX(usize),
    ApiResponseBodyTab(usize),
    ApiResponseHeadersTab(usize),
    ApiResponseCurlTab(usize),
    ApiResponseBody(usize),
    ApiResponseScrollY(usize),
    ApiResponseScrollX(usize),
    ApiResponseUseAccessToken(usize, usize),
    ApiResponseSaveRefreshToken(usize, usize),
    ApiTabBody,
    ApiMockServerToggle,
    ApiMockServerDetails,
    ApiMockServerCopyUrl,
    ApiMockServerDetailsClose,
    ApiMockServerLogArea,
    ApiMockServerLogScrollY,
    ApiMockModeSelect,
    ApiMockProxyBaseInput,
    ApiMockGuideOpen,
    ApiMockGuideClose,
    ApiMockGuideBody,
    ApiMockGuideScrollY,
    ApiMockPythonManage,
    ApiMockPythonManageClose,
    ApiMockPythonModeToggle,
    ApiMockPythonCheckRuntime,
    ApiMockPythonPrepareVersion,
    ApiMockPythonPickUvPath,
    ApiMockPythonPickCustomPath,
    ApiMockPythonVersionOption(usize),
    ApiMockPythonVersionsScrollY,
    ApiMockPythonInstallLogScrollY,
    ApiMockPythonUvPathInput,
    ApiMockPythonVersionInput,
    ApiMockPythonCustomPathInput,
    ApiMockExportOpenApi,
    ApiMockRouteEnable(usize),
    ApiMockRouteDetailsToggle(usize),
    ApiMockRoutePythonToggle(usize),
    ApiMockRouteReset(usize),
    ApiMockRouteResetConfirm,
    ApiMockRouteResetCancel,
    ApiMockContractPathToggle(usize),
    ApiMockContractQueryToggle(usize),
    ApiMockContractBodyToggle(usize),
    ApiMockContractPathFieldToggle(usize, usize),
    ApiMockContractQueryFieldToggle(usize, usize),
    ApiMockContractBodyFieldToggle(usize, usize),
    ApiMockContractFieldRequired(usize, ApiMockContractFieldGroup, usize),
    ApiMockContractFieldNullable(usize, ApiMockContractFieldGroup, usize),
    ApiMockContractFieldRemove(usize, ApiMockContractFieldGroup, usize),
    ApiMockContractFieldRemoveConfirm,
    ApiMockContractFieldRemoveCancel,
    ApiMockContractFieldPropInput(
        usize,
        ApiMockContractFieldGroup,
        usize,
        ApiMockContractFieldProp,
    ),
    ApiMockContractFieldAddConstraint(usize, ApiMockContractFieldGroup, usize),
    ApiMockContractFieldAddConstraintOption(
        usize,
        ApiMockContractFieldGroup,
        usize,
        ApiMockContractFieldProp,
    ),
    ApiMockStaticResponseInput(usize),
    ApiMockStaticResponseScrollY(usize),
    ApiMockStaticResponseScrollX(usize),
    ApiMockCombinedPython(usize),
    ApiMockCombinedScrollY(usize),
    ApiMockContractInput(usize),
    ApiMockSignatureInput(usize),
    ApiMockPreludeInput(usize),
    ApiMockBodyInput(usize),
    ApiMockContractReset(usize),
    ApiMockPreludeReset(usize),
    ApiMockBodyReset(usize),
    ApiMockAddInputField(usize),
    ApiMockAddOutputField(usize),
    ApiMockAddManualRoute,
    ApiMockManualRouteOpen(usize),
    ApiMockManualRouteMethod(usize),
    ApiMockManualRoutePath(usize),
    ApiMockManualRouteRemove(usize),

    // Database tools
    DatabasePanelBody,
    DatabaseGlobalErrorCopy,
    DatabaseAdd,
    DatabaseDelete,
    DatabaseRefresh,
    DatabaseConnectionRow(usize),
    DatabaseConnectionArrow(usize),
    DatabaseRow(usize, usize),
    DatabaseArrow(usize, usize),
    DatabaseTableRow(usize, usize, usize),
    PdfPage(usize),
    /// Whole PDF tab body; absorbs presses in margins and gaps and keeps the default cursor.
    PdfBody,
    /// One text line of a visible PDF page (I-beam cursor, start of a text selection).
    PdfText,
    /// Link `(page, index in the page's links)` of a visible PDF page.
    PdfLink(usize, usize),
    DatabaseContextItem(usize),
    DatabaseDialogBackdrop,
    DatabaseDialogBody,
    DatabaseDialogField(crate::app::database::DatabaseFormField),
    DatabaseDialogSecretEye(crate::app::database::DatabaseFormField),
    DatabaseDialogTls,
    DatabaseDialogColor,
    DatabaseDialogSshToggle,
    DatabaseDialogJumpToggle,
    DatabaseDialogRememberPostgres,
    DatabaseDialogRememberSshPassword,
    DatabaseDialogRememberSshPassphrase,
    DatabaseDialogRememberJumpPassword,
    DatabaseDialogRememberJumpPassphrase,
    DatabaseDialogTest,
    DatabaseDialogSave,
    DatabaseDialogCancel,
    DatabaseDeleteConfirm,
    DatabaseDeleteCancel,
    DatabaseHostKeyTrustOnce,
    DatabaseHostKeyTrustStore,
    DatabaseHostKeyCancel,
    DatabaseDdlBody,
    DatabaseDdlScroll,
    DatabaseTableBody,
    DatabaseTableUnavailableText,
    DatabaseTableAddRow,
    DatabaseTableDeleteRows,
    DatabaseTableUndo,
    DatabaseTableSave,
    DatabaseTablePreview,
    DatabaseTableRefresh,
    DatabaseTablePageFirst,
    DatabaseTablePagePrevious,
    DatabaseTablePageNext,
    DatabaseTablePageLast,
    DatabaseTableLimit,
    DatabaseTableWhereInput,
    DatabaseTableOrderInput,
    DatabaseTableHeader(usize),
    DatabaseTableColumnResize(usize),
    DatabaseGridRow(usize),
    DatabaseTableCell(usize, usize),
    DatabaseTableCellEditor,
    DatabaseTableEnumOption(usize),
    DatabaseTableEnumPreviousPage,
    DatabaseTableEnumNextPage,
    DatabaseTableDatePreviousMonth,
    DatabaseTableDateNextMonth,
    DatabaseTableDateDay(u8),
    DatabaseTableDateToday,
    DatabaseTableDateNow,
    DatabaseTableGridBody,
    DatabaseTableScrollY,
    DatabaseTableScrollX,
    DatabaseTableModalBackdrop,
    DatabaseTableModalBody,
    DatabaseTableModalInput,
    DatabaseTableModalPrimary,
    DatabaseTableModalSecondary,
    DatabaseTableModalTertiary,
    DatabaseTableModalScroll,
    DatabaseTableModalScrollX,
    DatabaseQueryRun,
    DatabaseQueryCancel,
    DatabaseQueryExplain,
    DatabaseQueryExplainAnalyze,
    DatabaseQueryFormat,
    DatabaseQueryHistory,
    DatabaseQueryNextDiagnostic,
    DatabaseQueryResultTab(usize),
    DatabaseQueryHistoryEntry(usize),
    DatabaseQueryResultBody,
    DatabaseQueryResultResize,
    DatabaseQueryColumnResize(usize),
    DatabaseQueryScrollY,
    DatabaseQueryScrollX,
    DatabaseQueryReviewBackdrop,
    DatabaseQueryReviewBody,
    DatabaseQueryReviewMessagesBody,
    DatabaseQueryReviewMessagesScrollY,
    DatabaseQueryCommit,
    DatabaseQueryRollback,

    // Git panel
    GitWorkspaceToggle(usize),
    GitFile(usize, usize),
    GitFileDiff(usize, usize),
    GitFolder(usize, usize),
    GitFolderStage(usize, usize),
    GitCommit,
    GitCommitMenuToggle,
    GitCommitMenuItem(usize),
    GitCommitOptionsToggle,
    GitCommitOptionsItem(usize),
    GitPush(usize),
    GitRollbackStaged(usize),
    GitStageAll(usize),
    GitUnstageAll(usize),
    GitRepoActionMenu(usize),
    GitFetch(usize),
    GitPull(usize),
    GitConfirmAction,
    GitConfirmCancel,
    GitMessageInput,
    GitRefresh,
    GitGraphToggle,
    GitLogsToggle,
    GitLogsClear,
    GitLogsBody,
    GitLogsScroll,
    GitWorkspaceScroll,
    GitGraphWorkspace(usize),
    GitGraphResize,
    GitGraphScroll,
    GitGraphCommit(usize, usize),
    GitGraphCopyCommit(usize, usize),
    GitGraphOpenCommit(usize, usize),

    // Sidebar
    SidebarSlot(crate::app::PanelId),

    // File tree
    FileTreeNode(usize),
    FileTreeArrow(usize),
    FileTreeScrollY,
    FileTreeMenuItem(usize),
    FileTreeCreateInput,
    FileTreeCreateConfirm,
    FileTreeCreateCancel,
    FileTreeRenameInput,
    FileTreeRenameConfirm,
    FileTreeRenameCancel,
    FileTreeMoveConfirm,
    FileTreeMoveCancel,
    FileTreeDeleteConfirm,
    FileTreeDeleteCancel,

    // Search
    SearchClose,
    SearchNext,
    SearchPrev,
    SearchCaseToggle,
    SearchInput,
    SearchPanelBody,

    // Project search
    ProjectSearchQueryInput,
    ProjectSearchIncludeInput,
    ProjectSearchExcludeInput,
    ProjectSearchFilterInput,
    ProjectSearchRun,
    ProjectSearchCaseToggle,
    ProjectSearchHelp,
    ProjectSearchHelpPopup,
    ProjectSearchFileToggle(usize),
    ProjectSearchMatchJump(usize, usize),
    ProjectSearchQueryScrollbarY,
    ProjectSearchQueryScrollbarX,
    ProjectSearchScrollbar,
    ProjectSearchPanelBody,

    // Tabs
    EditorTab(usize),
    EditorTabClose(usize),

    // Editor
    EditorFoldArrow(usize),
    EditorFoldDots(usize),
    EditorGitHunk(usize, usize),
    InlineGitPrevHunk,
    InlineGitNextHunk,
    InlineGitRollbackHunk,
    InlineGitPanelBody,
    GitDiffRollbackHunk(usize, usize),
    GitDiffPrevHunk,
    GitDiffNextHunk,
    GitDiffPanelBody,
    StickyLine(usize, usize),
    EditorScrollbarY,
    EditorScrollbarX,
    EditorTextBody,
    MarkdownReadBody,
    MarkdownReadScrollbar,
    MarkdownCodeCopy(usize),
    MarkdownCodeScrollbarX(usize),
    EditorMinimap,

    // Panels
    ResizeLeft,
    ResizeBottom,
    BottomPanelBody,
    LspLogArea(usize),
    LspScrollY,
    LspScrollX,
    LspLogScrollY(usize),
    LspLogScrollX(usize),
    CopyDiagnostic(usize),
    PopupCopyDiagnostic(usize),
    OpenDiagUrl(usize),
    PopupOpenDiagUrl(usize),
    ProblemJump(usize),
    ProblemUrl(usize),
    ProblemsTab(usize),
    ProblemFileToggle(usize),
    StatusBar,
    StatusDiagnostics,
    MarkdownModeToggle,
    MarkdownTocToggle,
    MarkdownTocItem(usize),
    PdfDarkToggle,
    PdfScrollY,
    /// "Download the PDF engine" / "Retry" button of the engine-missing screen.
    PdfEngineInstall,
    /// "Cancel" button of the engine download.
    PdfEngineCancel,
    TerminalBody,
    TerminalScrollY,
    TerminalTab(usize),
    TerminalTabClose(usize),
    TerminalAdd,
    TerminalSearchClose,
    TerminalSearchNext,
    TerminalSearchPrev,
    TerminalSearchCaseToggle,
    TerminalSearchInput,
    HoverPopupScroll,
}
